### PR TITLE
Update icons to Blueprint 3.33.0

### PR DESCRIPTION
**Pull request by fstephany**
This PR gets the latest icons from Blueprint. I've checked that one of the new one works (`IconName::ArrayNumeric`). It dd work but I don't know if there are any other thing to check?

### CODE REVIEW

**Comment by yozhgoor** [comment]
We are going to wait for #150 to be merged so we can directly check on the list of icons if you don't mind

**Comment by fstephany** [comment]
> We are going to wait for #150 to be merged so we can directly check on the list of icons if you don't mind

No worries!
It might even be easier to include this updated icon file in #150 maybe?

**Comment by cecton** [comment]
don't merge them separately and ignore the failing checks xD let's be pragmatic!

**Comment by yozhgoor** [comment]
Closing this PR in favor of #150

**Pull request closed without merging**
